package com.kodilla.exception.test;

public class Exception11 extends Exception{
    public void Show() {
        System.out.println("One of arguments is exceptions");// czemu tego nie wyświetla jak
        // zadziała catch

    }
}
